// Generated by CoffeeScript 1.6.1
(function() {
  var io;
  var connect = require('connect');
  connect.createServer(
    connect.static(__dirname)
  ).listen(8080);
  
  io = require('socket.io').listen(4000);

  io.sockets.on('connection', function(socket) {
    io.sockets.on('drawClick', function(data) {
      console.log("drawClick out");
      socket.broadcast.emit('draw', {
        x: data.x,
        y: data.y,
        type: data.type
      });
    });
  });

}).call(this);
